//*login
//? LOGIN POST
export const POST_LOGIN_REQUEST = 'POST_LOGIN_REQUEST';
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
export const POST_LOGIN_ERROR = 'POST_LOGIN_ERROR';

//*counters
//?All Counters 
export const GET_ALL_COUNTERS_REQUEST = 'GET_ALL_COUNTERS_REQUEST';
export const GET_ALL_COUNTERS_SUCCESS = 'GET_ALL_COUNTERS_SUCCESS';
export const GET_ALL_COUNTERS_ERROR = 'GET_ALL_COUNTERS_ERROR';

//?Counter by id
export const GET_COUNTER_BY_ID_REQUEST = 'GET_COUNTER_BY_ID_REQUEST';
export const GET_COUNTER_BY_ID_SUCCESS = 'GET_COUNTER_BY_ID_SUCCESS';
export const GET_COUNTER_BY_ID_ERROR = 'GET_COUNTER_BY_ID_ERROR';

//?Create Counter
export const CREATE_COUNTER_REQUEST = 'CREATE_COUNTER_REQUEST';
export const CREATE_COUNTER_SUCCESS = 'CREATE_COUNTER_SUCCESS';
export const CREATE_COUNTER_ERROR = 'CREATE_COUNTER_ERROR';

//?Update Counter
export const UPDATE_COUNTER_REQUEST = 'UPDATE_COUNTER_REQUEST';
export const UPDATE_COUNTER_SUCCESS = 'UPDATE_COUNTER_SUCCESS';
export const UPDATE_COUNTER_ERROR = 'UPDATE_COUNTER_ERROR';

//?Delete Counter
export const DELETE_COUNTER_REQUEST = 'DELETE_COUNTER_REQUEST';
export const DELETE_COUNTER_SUCCESS = 'DELETE_COUNTER_SUCCESS';
export const DELETE_COUNTER_ERROR = 'DELETE_COUNTER_ERROR';

//*system-notification
//?System Notification History
export const GET_SYSTEM_NOTI_HISTORY_REQUEST = 'GET_SYSTEM_NOTI_HISTORY_REQUEST';
export const GET_SYSTEM_NOTI_HISTORY_SUCCESS = 'GET_SYSTEM_NOTI_HISTORY_SUCCESS';
export const GET_SYSTEM_NOTI_HISTORY_ERROR = 'GET_SYSTEM_NOTI_HISTORY_ERROR';

//?Send System Notification 

export const POST_SYSTEM_NOTI_REQUEST = 'POST_SYSTEM_NOTI_REQUEST';
export const POST_SYSTEM_NOTI_SUCCESS = 'POST_SYSTEM_NOTI_SUCCESS';
export const POST_SYSTEM_NOTI_ERROR = 'POST_SYSTEM_NOTI_ERROR';

// All Admins
export const GET_ALL_ADMINS_REQUEST = 'GET_ALL_ADMINS_REQUEST';
export const GET_ALL_ADMINS_SUCCESS = 'GET_ALL_ADMINS_SUCCESS';
export const GET_ALL_ADMINS_ERROR = 'GET_ALL_ADMINS_ERROR';

// All Roles 
export const GET_ALL_ROLES_REQUEST = 'GET_ALL_ROLES_REQUEST';
export const GET_ALL_ROLES_SUCCESS = 'GET_ALL_ROLES_SUCCESS';
export const GET_ALL_ROLES_ERROR = 'GET_ALL_ROLES_ERROR';

// Counter by id
export const GET_ADMIN_BY_ID_REQUEST = 'GET_ADMIN_BY_ID_REQUEST';
export const GET_ADMIN_BY_ID_SUCCESS = 'GET_ADMIN_BY_ID_SUCCESS';
export const GET_ADMIN_BY_ID_ERROR = 'GET_ADMIN_BY_ID_ERROR';