//*login
//? LOGIN POST
export const POST_LOGIN_REQUEST = "POST_LOGIN_REQUEST";
export const POST_LOGIN_SUCCESS = "POST_LOGIN_SUCCESS";
export const POST_LOGIN_ERROR = "POST_LOGIN_ERROR";

//*counters
//?All Counters
export const GET_ALL_COUNTERS_REQUEST = "GET_ALL_COUNTERS_REQUEST";
export const GET_ALL_COUNTERS_SUCCESS = "GET_ALL_COUNTERS_SUCCESS";
export const GET_ALL_COUNTERS_ERROR = "GET_ALL_COUNTERS_ERROR";

//?Counter by id
export const GET_COUNTER_BY_ID_REQUEST = "GET_COUNTER_BY_ID_REQUEST";
export const GET_COUNTER_BY_ID_SUCCESS = "GET_COUNTER_BY_ID_SUCCESS";
export const GET_COUNTER_BY_ID_ERROR = "GET_COUNTER_BY_ID_ERROR";

//?Create Counter
export const CREATE_COUNTER_REQUEST = "CREATE_COUNTER_REQUEST";
export const CREATE_COUNTER_SUCCESS = "CREATE_COUNTER_SUCCESS";
export const CREATE_COUNTER_ERROR = "CREATE_COUNTER_ERROR";

export const GET_MAIN_COUNTER_PARCEL_DETAIL_REQUEST = 'GET_MAIN_COUNTER_PARCEL_DETAIL_REQUEST';
export const GET_MAIN_COUNTER_PARCEL_DETAIL_SUCCESS = 'GET_MAIN_COUNTER_PARCEL_DETAIL_SUCCESS';
export const GET_MAIN_COUNTER_PARCEL_DETAIL_ERROR = 'GET_MAIN_COUNTER_PARCEL_DETAIL_ERROR';



//?Update Counter
export const UPDATE_COUNTER_REQUEST = "UPDATE_COUNTER_REQUEST";
export const UPDATE_COUNTER_SUCCESS = "UPDATE_COUNTER_SUCCESS";
export const UPDATE_COUNTER_ERROR = "UPDATE_COUNTER_ERROR";

//?Delete Counter
export const DELETE_COUNTER_REQUEST = "DELETE_COUNTER_REQUEST";
export const DELETE_COUNTER_SUCCESS = "DELETE_COUNTER_SUCCESS";
export const DELETE_COUNTER_ERROR = "DELETE_COUNTER_ERROR";

//*system-notification
//?System Notification History
export const GET_SYSTEM_NOTI_HISTORY_REQUEST =
	"GET_SYSTEM_NOTI_HISTORY_REQUEST";
export const GET_SYSTEM_NOTI_HISTORY_SUCCESS =
	"GET_SYSTEM_NOTI_HISTORY_SUCCESS";
export const GET_SYSTEM_NOTI_HISTORY_ERROR = "GET_SYSTEM_NOTI_HISTORY_ERROR";

//?Send System Notification

export const POST_SYSTEM_NOTI_REQUEST = "POST_SYSTEM_NOTI_REQUEST";
export const POST_SYSTEM_NOTI_SUCCESS = "POST_SYSTEM_NOTI_SUCCESS";
export const POST_SYSTEM_NOTI_ERROR = "POST_SYSTEM_NOTI_ERROR";

//*application version
//?Version History
export const GET_VERSION_HISTORY_REQUEST = 'GET_VERSION_HISTORY_REQUEST';
export const GET_VERSION_HISTORY_SUCCESS = 'GET_VERSION_HISTORY_SUCCESS';
export const GET_VERSION_HISTORY_ERROR = 'GET_VERSION_HISTORY_ERROR';

//?Send new version 

export const POST_VERSION_REQUEST = 'POST_VERSION_REQUEST';
export const POST_VERSION_SUCCESS = 'POST_VERSION_SUCCESS';
export const POST_VERSION_ERROR = 'POST_VERSION_ERROR';

//*Upload image
//?Upload image
export const CREATE_IMAGE_REQUEST = 'CREATE_IMAGE_REQUEST';
export const CREATE_IMAGE_SUCCESS = 'CREATE_IMAGE_SUCCESS';
export const CREATE_IMAGE_ERROR = 'CREATE_IMAGE_ERROR';

//*Amount (Shipping fee)
//?All Amount (Shipping fee) 
export const GET_ALL_AMOUNTS_REQUEST = 'GET_ALL_AMOUNTS_REQUEST';
export const GET_ALL_AMOUNTS_SUCCESS = 'GET_ALL_AMOUNTS_SUCCESS';
export const GET_ALL_AMOUNTS_ERROR = 'GET_ALL_AMOUNTS_ERROR';

//?Amount by id
export const GET_AMOUNT_BY_ID_REQUEST = 'GET_AMOUNT_BY_ID_REQUEST';
export const GET_AMOUNT_BY_ID_SUCCESS = 'GET_AMOUNT_BY_ID_SUCCESS';
export const GET_AMOUNT_BY_ID_ERROR = 'GET_AMOUNT_BY_ID_ERROR';

//?Create AMOUNT
export const CREATE_AMOUNT_REQUEST = 'CREATE_AMOUNT_REQUEST';
export const CREATE_AMOUNT_SUCCESS = 'CREATE_AMOUNT_SUCCESS';
export const CREATE_AMOUNT_ERROR = 'CREATE_AMOUNT_ERROR';

//?Update AMOUNT
export const UPDATE_AMOUNT_REQUEST = 'UPDATE_AMOUNT_REQUEST';
export const UPDATE_AMOUNT_SUCCESS = 'UPDATE_AMOUNT_SUCCESS';
export const UPDATE_AMOUNT_ERROR = 'UPDATE_AMOUNT_ERROR';

//?Delete AMOUNT
export const DELETE_AMOUNT_REQUEST = 'DELETE_AMOUNT_REQUEST';
export const DELETE_AMOUNT_SUCCESS = 'DELETE_AMOUNT_SUCCESS';
export const DELETE_AMOUNT_ERROR = 'DELETE_AMOUNT_ERROR';


//*City (Branch)
//?All CITY 
export const GET_ALL_CITY_REQUEST = 'GET_ALL_CITY_REQUEST';
export const GET_ALL_CITY_SUCCESS = 'GET_ALL_CITY_SUCCESS';
export const GET_ALL_CITY_ERROR = 'GET_ALL_CITY_ERROR';

//?All CITY_FILTER 
export const GET_ALL_CITY_FILTER_REQUEST = 'GET_ALL_CITY_FILTER_REQUEST';
export const GET_ALL_CITY_FILTER_SUCCESS = 'GET_ALL_CITY_FILTER_SUCCESS';
export const GET_ALL_CITY_FILTER_ERROR = 'GET_ALL_CITY_FILTER_ERROR';

//?CITY by id
export const GET_CITY_BY_ID_REQUEST = 'GET_CITY_BY_ID_REQUEST';
export const GET_CITY_BY_ID_SUCCESS = 'GET_CITY_BY_ID_SUCCESS';
export const GET_CITY_BY_ID_ERROR = 'GET_CITY_BY_ID_ERROR';

//?Create CITY
export const CREATE_CITY_REQUEST = 'CREATE_CITY_REQUEST';
export const CREATE_CITY_SUCCESS = 'CREATE_CITY_SUCCESS';
export const CREATE_CITY_ERROR = 'CREATE_CITY_ERROR';

//?Update CITY
export const UPDATE_CITY_REQUEST = 'UPDATE_CITY_REQUEST';
export const UPDATE_CITY_SUCCESS = 'UPDATE_CITY_SUCCESS';
export const UPDATE_CITY_ERROR = 'UPDATE_CITY_ERROR';

//?Delete CITY
export const DELETE_CITY_REQUEST = 'DELETE_CITY_REQUEST';
export const DELETE_CITY_SUCCESS = 'DELETE_CITY_SUCCESS';
export const DELETE_CITY_ERROR = 'DELETE_CITY_ERROR';

//*HELP_CENTER (Branch)
//?All HELP_CENTER 
export const GET_ALL_HELP_CENTER_REQUEST = 'GET_ALL_HELP_CENTER_REQUEST';
export const GET_ALL_HELP_CENTER_SUCCESS = 'GET_ALL_HELP_CENTER_SUCCESS';
export const GET_ALL_HELP_CENTER_ERROR = 'GET_ALL_HELP_CENTER_ERROR';

//?All HELP_CENTER_FILTER 
export const GET_ALL_HELP_CENTER_FILTER_REQUEST = 'GET_ALL_HELP_CENTER_FILTER_REQUEST';
export const GET_ALL_HELP_CENTER_FILTER_SUCCESS = 'GET_ALL_HELP_CENTER_FILTER_SUCCESS';
export const GET_ALL_HELP_CENTER_FILTER_ERROR = 'GET_ALL_HELP_CENTER_FILTER_ERROR';

//?HELP_CENTER by id
export const GET_HELP_CENTER_BY_ID_REQUEST = 'GET_HELP_CENTER_BY_ID_REQUEST';
export const GET_HELP_CENTER_BY_ID_SUCCESS = 'GET_HELP_CENTER_BY_ID_SUCCESS';
export const GET_HELP_CENTER_BY_ID_ERROR = 'GET_HELP_CENTER_BY_ID_ERROR';

//?Create HELP_CENTER
export const CREATE_HELP_CENTER_REQUEST = 'CREATE_HELP_CENTER_REQUEST';
export const CREATE_HELP_CENTER_SUCCESS = 'CREATE_HELP_CENTER_SUCCESS';
export const CREATE_HELP_CENTER_ERROR = 'CREATE_HELP_CENTER_ERROR';

//?Update HELP_CENTER
export const UPDATE_HELP_CENTER_REQUEST = 'UPDATE_HELP_CENTER_REQUEST';
export const UPDATE_HELP_CENTER_SUCCESS = 'UPDATE_HELP_CENTER_SUCCESS';
export const UPDATE_HELP_CENTER_ERROR = 'UPDATE_HELP_CENTER_ERROR';

//?Delete HELP_CENTER
export const DELETE_HELP_CENTER_REQUEST = 'DELETE_HELP_CENTER_REQUEST';
export const DELETE_HELP_CENTER_SUCCESS = 'DELETE_HELP_CENTER_SUCCESS';
export const DELETE_HELP_CENTER_ERROR = 'DELETE_HELP_CENTER_ERROR';

//*Block
//?All BLOCK 
export const GET_ALL_BLOCK_REQUEST = 'GET_ALL_BLOCK_REQUEST';
export const GET_ALL_BLOCK_SUCCESS = 'GET_ALL_BLOCK_SUCCESS';
export const GET_ALL_BLOCK_ERROR = 'GET_ALL_BLOCK_ERROR';

//?All BLOCK_FILTER 
export const GET_ALL_BLOCK_FILTER_REQUEST = 'GET_ALL_BLOCK_FILTER_REQUEST';
export const GET_ALL_BLOCK_FILTER_SUCCESS = 'GET_ALL_BLOCK_FILTER_SUCCESS';
export const GET_ALL_BLOCK_FILTER_ERROR = 'GET_ALL_BLOCK_FILTER_ERROR';

//?BLOCK by id
export const GET_BLOCK_BY_ID_REQUEST = 'GET_BLOCK_BY_ID_REQUEST';
export const GET_BLOCK_BY_ID_SUCCESS = 'GET_BLOCK_BY_ID_SUCCESS';
export const GET_BLOCK_BY_ID_ERROR = 'GET_BLOCK_BY_ID_ERROR';

//?Create BLOCK
export const CREATE_BLOCK_REQUEST = 'CREATE_BLOCK_REQUEST';
export const CREATE_BLOCK_SUCCESS = 'CREATE_BLOCK_SUCCESS';
export const CREATE_BLOCK_ERROR = 'CREATE_BLOCK_ERROR';

//?Update BLOCK
export const UPDATE_BLOCK_REQUEST = 'UPDATE_BLOCK_REQUEST';
export const UPDATE_BLOCK_SUCCESS = 'UPDATE_BLOCK_SUCCESS';
export const UPDATE_BLOCK_ERROR = 'UPDATE_BLOCK_ERROR';

//?Delete BLOCK
export const DELETE_BLOCK_REQUEST = 'DELETE_BLOCK_REQUEST';
export const DELETE_BLOCK_SUCCESS = 'DELETE_BLOCK_SUCCESS';
export const DELETE_BLOCK_ERROR = 'DELETE_BLOCK_ERROR';

//*MODULE
//?All MODULE 
export const GET_ALL_MODULE_REQUEST = 'GET_ALL_MODULE_REQUEST';
export const GET_ALL_MODULE_SUCCESS = 'GET_ALL_MODULE_SUCCESS';
export const GET_ALL_MODULE_ERROR = 'GET_ALL_MODULE_ERROR';

//*ROLE_ITEM
//?All ROLE_ITEM 
export const GET_ALL_ROLE_ITEM_REQUEST = 'GET_ALL_ROLE_ITEM_REQUEST';
export const GET_ALL_ROLE_ITEM_SUCCESS = 'GET_ALL_ROLE_ITEM_SUCCESS';
export const GET_ALL_ROLE_ITEM_ERROR = 'GET_ALL_ROLE_ITEM_ERROR';

//?All ROLE_ITEM_FILTER 
export const GET_ALL_ROLE_ITEM_FILTER_REQUEST = 'GET_ALL_ROLE_ITEM_FILTER_REQUEST';
export const GET_ALL_ROLE_ITEM_FILTER_SUCCESS = 'GET_ALL_ROLE_ITEM_FILTER_SUCCESS';
export const GET_ALL_ROLE_ITEM_FILTER_ERROR = 'GET_ALL_ROLE_ITEM_FILTER_ERROR';

//?ROLE_ITEM by id
export const GET_ROLE_ITEM_BY_ID_REQUEST = 'GET_ROLE_ITEM_BY_ID_REQUEST';
export const GET_ROLE_ITEM_BY_ID_SUCCESS = 'GET_ROLE_ITEM_BY_ID_SUCCESS';
export const GET_ROLE_ITEM_BY_ID_ERROR = 'GET_ROLE_ITEM_BY_ID_ERROR';

//?Create ROLE_ITEM
export const CREATE_ROLE_ITEM_REQUEST = 'CREATE_ROLE_ITEM_REQUEST';
export const CREATE_ROLE_ITEM_SUCCESS = 'CREATE_ROLE_ITEM_SUCCESS';
export const CREATE_ROLE_ITEM_ERROR = 'CREATE_ROLE_ITEM_ERROR';

//?Update ROLE_ITEM
export const UPDATE_ROLE_ITEM_REQUEST = 'UPDATE_ROLE_ITEM_REQUEST';
export const UPDATE_ROLE_ITEM_SUCCESS = 'UPDATE_ROLE_ITEM_SUCCESS';
export const UPDATE_ROLE_ITEM_ERROR = 'UPDATE_ROLE_ITEM_ERROR';

//?Delete ROLE_ITEM
export const DELETE_ROLE_ITEM_REQUEST = 'DELETE_ROLE_ITEM_REQUEST';
export const DELETE_ROLE_ITEM_SUCCESS = 'DELETE_ROLE_ITEM_SUCCESS';
export const DELETE_ROLE_ITEM_ERROR = 'DELETE_ROLE_ITEM_ERROR';

//*REGION
//?All REGION 
export const GET_ALL_REGION_REQUEST = 'GET_ALL_REGION_REQUEST';
export const GET_ALL_REGION_SUCCESS = 'GET_ALL_REGION_SUCCESS';
export const GET_ALL_REGION_ERROR = 'GET_ALL_REGION_ERROR';

//?All REGION_FILTER 
export const GET_ALL_REGION_FILTER_REQUEST = 'GET_ALL_REGION_FILTER_REQUEST';
export const GET_ALL_REGION_FILTER_SUCCESS = 'GET_ALL_REGION_FILTER_SUCCESS';
export const GET_ALL_REGION_FILTER_ERROR = 'GET_ALL_REGION_FILTER_ERROR';

//?REGION by id
export const GET_REGION_BY_ID_REQUEST = 'GET_REGION_BY_ID_REQUEST';
export const GET_REGION_BY_ID_SUCCESS = 'GET_REGION_BY_ID_SUCCESS';
export const GET_REGION_BY_ID_ERROR = 'GET_REGION_BY_ID_ERROR';

//?Create REGION
export const CREATE_REGION_REQUEST = 'CREATE_REGION_REQUEST';
export const CREATE_REGION_SUCCESS = 'CREATE_REGION_SUCCESS';
export const CREATE_REGION_ERROR = 'CREATE_REGION_ERROR';

//?Update REGION
export const UPDATE_REGION_REQUEST = 'UPDATE_REGION_REQUEST';
export const UPDATE_REGION_SUCCESS = 'UPDATE_REGION_SUCCESS';
export const UPDATE_REGION_ERROR = 'UPDATE_REGION_ERROR';

//?Delete REGION
export const DELETE_REGION_REQUEST = 'DELETE_REGION_REQUEST';
export const DELETE_REGION_SUCCESS = 'DELETE_REGION_SUCCESS';
export const DELETE_REGION_ERROR = 'DELETE_REGION_ERROR';

//*APP_BANNER
//?All APP_BANNER 
export const GET_ALL_APP_BANNER_REQUEST = 'GET_ALL_APP_BANNER_REQUEST';
export const GET_ALL_APP_BANNER_SUCCESS = 'GET_ALL_APP_BANNER_SUCCESS';
export const GET_ALL_APP_BANNER_ERROR = 'GET_ALL_APP_BANNER_ERROR';

//?All APP_BANNER_FILTER 
export const GET_ALL_APP_BANNER_FILTER_REQUEST = 'GET_ALL_APP_BANNER_FILTER_REQUEST';
export const GET_ALL_APP_BANNER_FILTER_SUCCESS = 'GET_ALL_APP_BANNER_FILTER_SUCCESS';
export const GET_ALL_APP_BANNER_FILTER_ERROR = 'GET_ALL_APP_BANNER_FILTER_ERROR';

//?APP_BANNER by id
export const GET_APP_BANNER_BY_ID_REQUEST = 'GET_APP_BANNER_BY_ID_REQUEST';
export const GET_APP_BANNER_BY_ID_SUCCESS = 'GET_APP_BANNER_BY_ID_SUCCESS';
export const GET_APP_BANNER_BY_ID_ERROR = 'GET_APP_BANNER_BY_ID_ERROR';

//?Create APP_BANNER
export const CREATE_APP_BANNER_REQUEST = 'CREATE_APP_BANNER_REQUEST';
export const CREATE_APP_BANNER_SUCCESS = 'CREATE_APP_BANNER_SUCCESS';
export const CREATE_APP_BANNER_ERROR = 'CREATE_APP_BANNER_ERROR';

//?Update APP_BANNER
export const UPDATE_APP_BANNER_REQUEST = 'UPDATE_APP_BANNER_REQUEST';
export const UPDATE_APP_BANNER_SUCCESS = 'UPDATE_APP_BANNER_SUCCESS';
export const UPDATE_APP_BANNER_ERROR = 'UPDATE_APP_BANNER_ERROR';

//?Delete APP_BANNER
export const DELETE_APP_BANNER_REQUEST = 'DELETE_APP_BANNER_REQUEST';
export const DELETE_APP_BANNER_SUCCESS = 'DELETE_APP_BANNER_SUCCESS';
export const DELETE_APP_BANNER_ERROR = 'DELETE_APP_BANNER_ERROR';

//*BANNER
//?All BANNER 
export const GET_ALL_BANNER_REQUEST = 'GET_ALL_BANNER_REQUEST';
export const GET_ALL_BANNER_SUCCESS = 'GET_ALL_BANNER_SUCCESS';
export const GET_ALL_BANNER_ERROR = 'GET_ALL_BANNER_ERROR';

//?All BANNER_FILTER 
export const GET_ALL_BANNER_FILTER_REQUEST = 'GET_ALL_BANNER_FILTER_REQUEST';
export const GET_ALL_BANNER_FILTER_SUCCESS = 'GET_ALL_BANNER_FILTER_SUCCESS';
export const GET_ALL_BANNER_FILTER_ERROR = 'GET_ALL_BANNER_FILTER_ERROR';

//?BANNER by id
export const GET_BANNER_BY_ID_REQUEST = 'GET_BANNER_BY_ID_REQUEST';
export const GET_BANNER_BY_ID_SUCCESS = 'GET_BANNER_BY_ID_SUCCESS';
export const GET_BANNER_BY_ID_ERROR = 'GET_BANNER_BY_ID_ERROR';

//?Create BANNER
export const CREATE_BANNER_REQUEST = 'CREATE_BANNER_REQUEST';
export const CREATE_BANNER_SUCCESS = 'CREATE_BANNER_SUCCESS';
export const CREATE_BANNER_ERROR = 'CREATE_BANNER_ERROR';

//?Update BANNER
export const UPDATE_BANNER_REQUEST = 'UPDATE_BANNER_REQUEST';
export const UPDATE_BANNER_SUCCESS = 'UPDATE_BANNER_SUCCESS';
export const UPDATE_BANNER_ERROR = 'UPDATE_BANNER_ERROR';

//?Delete BANNER
export const DELETE_BANNER_REQUEST = 'DELETE_BANNER_REQUEST';
export const DELETE_BANNER_SUCCESS = 'DELETE_BANNER_SUCCESS';
export const DELETE_BANNER_ERROR = 'DELETE_BANNER_ERROR';

//*JUST_ANNER
//?All JUST_BANNER 
export const GET_ALL_JUST_BANNER_REQUEST = 'GET_ALL_JUST_BANNER_REQUEST';
export const GET_ALL_JUST_BANNER_SUCCESS = 'GET_ALL_JUST_BANNER_SUCCESS';
export const GET_ALL_JUST_BANNER_ERROR = 'GET_ALL_JUST_BANNER_ERROR';

//?All JUST_BANNER_FILTER 
export const GET_ALL_JUST_BANNER_FILTER_REQUEST = 'GET_ALL_JUST_BANNER_FILTER_REQUEST';
export const GET_ALL_JUST_BANNER_FILTER_SUCCESS = 'GET_ALL_JUST_BANNER_FILTER_SUCCESS';
export const GET_ALL_JUST_BANNER_FILTER_ERROR = 'GET_ALL_JUST_BANNER_FILTER_ERROR';

//?JUST_BANNER by id
export const GET_JUST_BANNER_BY_ID_REQUEST = 'GET_JUST_BANNER_BY_ID_REQUEST';
export const GET_JUST_BANNER_BY_ID_SUCCESS = 'GET_JUST_BANNER_BY_ID_SUCCESS';
export const GET_JUST_BANNER_BY_ID_ERROR = 'GET_JUST_BANNER_BY_ID_ERROR';

//?Create JUST_BANNER
export const CREATE_JUST_BANNER_REQUEST = 'CREATE_JUST_BANNER_REQUEST';
export const CREATE_JUST_BANNER_SUCCESS = 'CREATE_JUST_BANNER_SUCCESS';
export const CREATE_JUST_BANNER_ERROR = 'CREATE_JUST_BANNER_ERROR';

//?Update JUST_BANNER
export const UPDATE_JUST_BANNER_REQUEST = 'UPDATE_JUST_BANNER_REQUEST';
export const UPDATE_JUST_BANNER_SUCCESS = 'UPDATE_JUST_BANNER_SUCCESS';
export const UPDATE_JUST_BANNER_ERROR = 'UPDATE_JUST_BANNER_ERROR';

//?Delete JUST_BANNER
export const DELETE_JUST_BANNER_REQUEST = 'DELETE_JUST_BANNER_REQUEST';
export const DELETE_JUST_BANNER_SUCCESS = 'DELETE_JUST_BANNER_SUCCESS';
export const DELETE_JUST_BANNER_ERROR = 'DELETE_JUST_BANNER_ERROR';

//*ROLE
//?All ROLE 
export const GET_ALL_ROLE_REQUEST = 'GET_ALL_ROLE_REQUEST';
export const GET_ALL_ROLE_SUCCESS = 'GET_ALL_ROLE_SUCCESS';
export const GET_ALL_ROLE_ERROR = 'GET_ALL_ROLE_ERROR';

//?All ROLE_FILTER 
export const GET_ALL_ROLE_FILTER_REQUEST = 'GET_ALL_ROLE_FILTER_REQUEST';
export const GET_ALL_ROLE_FILTER_SUCCESS = 'GET_ALL_ROLE_FILTER_SUCCESS';
export const GET_ALL_ROLE_FILTER_ERROR = 'GET_ALL_ROLE_FILTER_ERROR';

//?ROLE by id
export const GET_ROLE_BY_ID_REQUEST = 'GET_ROLE_BY_ID_REQUEST';
export const GET_ROLE_BY_ID_SUCCESS = 'GET_ROLE_BY_ID_SUCCESS';
export const GET_ROLE_BY_ID_ERROR = 'GET_ROLE_BY_ID_ERROR';

//?Create ROLE
export const CREATE_ROLE_REQUEST = 'CREATE_ROLE_REQUEST';
export const CREATE_ROLE_SUCCESS = 'CREATE_ROLE_SUCCESS';
export const CREATE_ROLE_ERROR = 'CREATE_ROLE_ERROR';

//?Update ROLE
export const UPDATE_ROLE_REQUEST = 'UPDATE_ROLE_REQUEST';
export const UPDATE_ROLE_SUCCESS = 'UPDATE_ROLE_SUCCESS';
export const UPDATE_ROLE_ERROR = 'UPDATE_ROLE_ERROR';

//?Delete ROLE
export const DELETE_ROLE_REQUEST = 'DELETE_ROLE_REQUEST';
export const DELETE_ROLE_SUCCESS = 'DELETE_ROLE_SUCCESS';
export const DELETE_ROLE_ERROR = 'DELETE_ROLE_ERROR';

//*USER_GUIDE
//?All USER_GUIDE 
export const SEND_USER_GUIDE_REQUEST = 'SEND_USER_GUIDE_REQUEST';
export const SEND_USER_GUIDE_SUCCESS = 'SEND_USER_GUIDE_SUCCESS';
export const SEND_USER_GUIDE_ERROR = 'SEND_USER_GUIDE_ERROR';

//*TERMS_AND_POLICY
//?All TERMS_AND_POLICY 
export const SEND_TERMS_AND_POLICY_REQUEST = 'SEND_TERMS_AND_POLICY_REQUEST';
export const SEND_TERMS_AND_POLICY_SUCCESS = 'SEND_TERMS_AND_POLICY_SUCCESS';
export const SEND_TERMS_AND_POLICY_ERROR = 'SEND_TERMS_AND_POLICY_ERROR';

//*PAYMENT
//?All PAYMENT 
export const GET_ALL_PAYMENT_REQUEST = 'GET_ALL_PAYMENT_REQUEST';
export const GET_ALL_PAYMENT_SUCCESS = 'GET_ALL_PAYMENT_SUCCESS';
export const GET_ALL_PAYMENT_ERROR = 'GET_ALL_PAYMENT_ERROR';

//?All PAYMENT_FILTER 
export const GET_ALL_PAYMENT_FILTER_REQUEST = 'GET_ALL_PAYMENT_FILTER_REQUEST';
export const GET_ALL_PAYMENT_FILTER_SUCCESS = 'GET_ALL_PAYMENT_FILTER_SUCCESS';
export const GET_ALL_PAYMENT_FILTER_ERROR = 'GET_ALL_PAYMENT_FILTER_ERROR';

//?PAYMENT by id
export const GET_PAYMENT_BY_ID_REQUEST = 'GET_PAYMENT_BY_ID_REQUEST';
export const GET_PAYMENT_BY_ID_SUCCESS = 'GET_PAYMENT_BY_ID_SUCCESS';
export const GET_PAYMENT_BY_ID_ERROR = 'GET_PAYMENT_BY_ID_ERROR';

//?Create PAYMENT
export const CREATE_PAYMENT_REQUEST = 'CREATE_PAYMENT_REQUEST';
export const CREATE_PAYMENT_SUCCESS = 'CREATE_PAYMENT_SUCCESS';
export const CREATE_PAYMENT_ERROR = 'CREATE_PAYMENT_ERROR';

//?Update PAYMENT
export const UPDATE_PAYMENT_REQUEST = 'UPDATE_PAYMENT_REQUEST';
export const UPDATE_PAYMENT_SUCCESS = 'UPDATE_PAYMENT_SUCCESS';
export const UPDATE_PAYMENT_ERROR = 'UPDATE_PAYMENT_ERROR';

//?Delete PAYMENT
export const DELETE_PAYMENT_REQUEST = 'DELETE_PAYMENT_REQUEST';
export const DELETE_PAYMENT_SUCCESS = 'DELETE_PAYMENT_SUCCESS';
export const DELETE_PAYMENT_ERROR = 'DELETE_PAYMENT_ERROR';

//*Currency
//?All CURRENCY 
export const GET_ALL_CURRENCY_REQUEST = 'GET_ALL_CURRENCY_REQUEST';
export const GET_ALL_CURRENCY_SUCCESS = 'GET_ALL_CURRENCY_SUCCESS';
export const GET_ALL_CURRENCY_ERROR = 'GET_ALL_CURRENCY_ERROR';

//?CURRENCY by id
export const GET_CURRENCY_BY_ID_REQUEST = 'GET_CURRENCY_BY_ID_REQUEST';
export const GET_CURRENCY_BY_ID_SUCCESS = 'GET_CURRENCY_BY_ID_SUCCESS';
export const GET_CURRENCY_BY_ID_ERROR = 'GET_CURRENCY_BY_ID_ERROR';

//?Create CURRENCY
export const CREATE_CURRENCY_REQUEST = 'CREATE_CURRENCY_REQUEST';
export const CREATE_CURRENCY_SUCCESS = 'CREATE_CURRENCY_SUCCESS';
export const CREATE_CURRENCY_ERROR = 'CREATE_CURRENCY_ERROR';

//?Update CURRENCY
export const UPDATE_CURRENCY_REQUEST = 'UPDATE_CURRENCY_REQUEST';
export const UPDATE_CURRENCY_SUCCESS = 'UPDATE_CURRENCY_SUCCESS';
export const UPDATE_CURRENCY_ERROR = 'UPDATE_CURRENCY_ERROR';

//?Delete CURRENCY
export const DELETE_CURRENCY_REQUEST = 'DELETE_CURRENCY_REQUEST';
export const DELETE_CURRENCY_SUCCESS = 'DELETE_CURRENCY_SUCCESS';
export const DELETE_CURRENCY_ERROR = 'DELETE_CURRENCY_ERROR';

//*WEIGHT
//?All WEIGHT 
export const GET_ALL_WEIGHT_REQUEST = 'GET_ALL_WEIGHT_REQUEST';
export const GET_ALL_WEIGHT_SUCCESS = 'GET_ALL_WEIGHT_SUCCESS';
export const GET_ALL_WEIGHT_ERROR = 'GET_ALL_WEIGHT_ERROR';

//?WEIGHT by id
export const GET_WEIGHT_BY_ID_REQUEST = 'GET_WEIGHT_BY_ID_REQUEST';
export const GET_WEIGHT_BY_ID_SUCCESS = 'GET_WEIGHT_BY_ID_SUCCESS';
export const GET_WEIGHT_BY_ID_ERROR = 'GET_WEIGHT_BY_ID_ERROR';

//?Create WEIGHT
export const CREATE_WEIGHT_REQUEST = 'CREATE_WEIGHT_REQUEST';
export const CREATE_WEIGHT_SUCCESS = 'CREATE_WEIGHT_SUCCESS';
export const CREATE_WEIGHT_ERROR = 'CREATE_WEIGHT_ERROR';

//?Update WEIGHT
export const UPDATE_WEIGHT_REQUEST = 'UPDATE_WEIGHT_REQUEST';
export const UPDATE_WEIGHT_SUCCESS = 'UPDATE_WEIGHT_SUCCESS';
export const UPDATE_WEIGHT_ERROR = 'UPDATE_WEIGHT_ERROR';

//?Delete WEIGHT
export const DELETE_WEIGHT_REQUEST = 'DELETE_WEIGHT_REQUEST';
export const DELETE_WEIGHT_SUCCESS = 'DELETE_WEIGHT_SUCCESS';
export const DELETE_WEIGHT_ERROR = 'DELETE_WEIGHT_ERROR';

//*PARCEL
//?All PARCEL 
export const GET_ALL_PARCEL_REQUEST = 'GET_ALL_PARCEL_REQUEST';
export const GET_ALL_PARCEL_SUCCESS = 'GET_ALL_PARCEL_SUCCESS';
export const GET_ALL_PARCEL_ERROR = 'GET_ALL_PARCEL_ERROR';
//?All PARCEL_FILTER 
export const GET_ALL_PARCEL_FILTER_REQUEST = 'GET_ALL_PARCEL_FILTER_REQUEST';
export const GET_ALL_PARCEL_FILTER_SUCCESS = 'GET_ALL_PARCEL_FILTER_SUCCESS';
export const GET_ALL_PARCEL_FILTER_ERROR = 'GET_ALL_PARCEL_FILTER_ERROR';

//?PARCEL by id
export const GET_PARCEL_BY_ID_REQUEST = 'GET_PARCEL_BY_ID_REQUEST';
export const GET_PARCEL_BY_ID_SUCCESS = 'GET_PARCEL_BY_ID_SUCCESS';
export const GET_PARCEL_BY_ID_ERROR = 'GET_PARCEL_BY_ID_ERROR';

//?Create PARCEL
export const CREATE_PARCEL_REQUEST = 'CREATE_PARCEL_REQUEST';
export const CREATE_PARCEL_SUCCESS = 'CREATE_PARCEL_SUCCESS';
export const CREATE_PARCEL_ERROR = 'CREATE_PARCEL_ERROR';

//?Update PARCEL
export const UPDATE_PARCEL_REQUEST = 'UPDATE_PARCEL_REQUEST';
export const UPDATE_PARCEL_SUCCESS = 'UPDATE_PARCEL_SUCCESS';
export const UPDATE_PARCEL_ERROR = 'UPDATE_PARCEL_ERROR';

//?Delete PARCEL
export const DELETE_PARCEL_REQUEST = 'DELETE_PARCEL_REQUEST';
export const DELETE_PARCEL_SUCCESS = 'DELETE_PARCEL_SUCCESS';
export const DELETE_PARCEL_ERROR = 'DELETE_PARCEL_ERROR';

// All Admins
export const GET_ALL_ADMINS_REQUEST = "GET_ALL_ADMINS_REQUEST";
export const GET_ALL_ADMINS_SUCCESS = "GET_ALL_ADMINS_SUCCESS";
export const GET_ALL_ADMINS_ERROR = "GET_ALL_ADMINS_ERROR";

// All Roles
export const GET_ALL_ROLES_REQUEST = "GET_ALL_ROLES_REQUEST";
export const GET_ALL_ROLES_SUCCESS = "GET_ALL_ROLES_SUCCESS";
export const GET_ALL_ROLES_ERROR = "GET_ALL_ROLES_ERROR";

// Counter by id
export const GET_ADMIN_BY_ID_REQUEST = 'GET_ADMIN_BY_ID_REQUEST';
export const GET_ADMIN_BY_ID_SUCCESS = 'GET_ADMIN_BY_ID_SUCCESS';
export const GET_ADMIN_BY_ID_ERROR = 'GET_ADMIN_BY_ID_ERROR';

//?Create Admin 
export const CREATE_ADMIN_REQUEST = "CREATE_ADMIN_REQUEST";
export const CREATE_ADMIN_SUCCESS = "CREATE_ADMIN_SUCCESS";
export const CREATE_ADMIN_ERROR = "CREATE_ADMIN_ERROR";

//?Update Admin
export const UPDATE_ADMIN_REQUEST = "UPDATE_ADMIN_REQUEST";
export const UPDATE_ADMIN_SUCCESS = "UPDATE_ADMIN_SUCCESS";
export const UPDATE_ADMIN_ERROR = "UPDATE_ADMIN_ERROR";

//?Delete Admin
export const DELETE_ADMIN_REQUEST = "DELETE_ADMIN_REQUEST";
export const DELETE_ADMIN_SUCCESS = "DELETE_ADMIN_SUCCESS";
export const DELETE_ADMIN_ERROR = "DELETE_ADMIN_ERROR";

// Regions
export const GET_ALL_REGIONS_REQUEST = "GET_ALL_REGIONS_REQUEST";
export const GET_ALL_REGIONS_SUCCESS = "GET_ALL_REGIONS_SUCCESS";
export const GET_ALL_REGIONS_ERROR = "GET_ALL_REGIONS_ERROR";

// City
export const GET_ALL_CITIES_REQUEST = "GET_ALL_cityS_REQUEST";
export const GET_ALL_CITIES_SUCCESS = "GET_ALL_cityS_SUCCESS";
export const GET_ALL_CITIES_ERROR = "GET_ALL_cityS_ERROR";

// Block
export const GET_ALL_BLOCKS_REQUEST = "GET_ALL_BLOCKS_REQUEST";
export const GET_ALL_BLOCKS_SUCCESS = "GET_ALL_BLOCKS_SUCCESS";
export const GET_ALL_BLOCKS_ERROR = "GET_ALL_BLOCKS_ERROR";

// Report
export const GET_ALL_REPORTS_REQUEST = "GET_ALL_REPORTS_REQUEST";
export const GET_ALL_REPORTS_SUCCESS = "GET_ALL_REPORTS_SUCCESS";
export const GET_ALL_REPORTS_ERROR = "GET_ALL_REPORTS_ERROR";

// Daily Income Report
export const GET_ALL_DAILY_INCOME_REPORT_REQUEST = "GET_ALL_DAILY_INCOME_REPORT_REQUEST";
export const GET_ALL_DAILY_INCOME_REPORT_SUCCESS = "GET_ALL_DAILY_INCOME_REPORT_SUCCESS";
export const GET_ALL_DAILY_INCOME_REPORT_ERROR = "GET_ALL_DAILY_INCOME_REPORT_ERROR";
